version: '3'

services:
  header:
    build: header-sidebar-service/
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  # results:
  #   build: results_server/
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3000:3000'

  database:
    image: mysql:5.7.24
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

# docker run -d --name mysqlDB --env="MYSQL_ALLOW_EMPTY_PASSWORD=yes" --network header-network mysql:5.7.24
# docker build --network header-network -t header .
# docker run -d -p 3003:3003 -v $(pwd):/src/app --name headersidebar --net header-network header